--- #YAML:1.0
name:                DBIx-Report-Excel
version:             0.1
abstract:            creating Excel reports from SQL statements
license:             ~
author:              
    - Dmytro Kovalov <dmytro.kovalov@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Tabular::Dumper:         0.06
    Data::Tabular::Dumper::Excel:  0
    SQL::Parser:                   1.16
    SQL::Script:                   1.05
    YAML:                          0.68
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
