# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Report-Excel
version:      0.1b
version_from: lib/DBIx/Report/Excel.pm
installdirs:  site
requires:
    Data::Tabular::Dumper:         0.06
    Data::Tabular::Dumper::Excel:  0
    Spreadsheet::WriteExcel:       0
    SQL::Parser:                   1.16
    SQL::Script:                   1.05
    YAML:                          0.68

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
